config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :hotels, only: [:index, :show, :new, :create, :destroy] do
    scope module: 'hotels' do
      resources :feedbacks
    end

  end

  root to: 'hotels#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  validates :placement, inclusion: 1..5
  validates :cleanliness, inclusion: 1..5
  validates :communication, inclusion: 1..5

  scope :persisted, ->(hotel_id) {
    where(hotel_id: hotel_id)
  }
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :feedbacks, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :feedbacks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:admin, :user]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels/feedbacks_controller.rb
module Hotels
  class FeedbacksController < ApplicationController
    before_action :find_hotel

    def index
      @feedbacks = @hotel.feedbacks
    end

    def create
      @feedback = @hotel.feedbacks.build(allowed_params.merge(user_id: current_user.id))
      @feedback_owner = @feedback.user.email
      if @feedback.save
        redirect_to  hotel_path(@hotel)
      else
        @presenter = Hotels::IndexPresenter.new(@hotel)
        render template: 'hotels/show'
      end
    end

    private
    def allowed_params
      params.require(:feedback).permit(
        :review,
        :cleanliness,
        :communication,
        :placement)
    end

    def find_hotel
      @hotel = Hotel.find(params[:hotel_id])
    end
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  class Forbidden < StandardError; end
  before_action :authenticate_user!
  before_action :admin?, except: [:index, :show]

  def index
    @hotels = Hotel.all
  end

  def show
    @hotel = Hotel.find(params[:id])
    @feedback = @hotel.feedbacks.build
    @presenter = Hotels::IndexPresenter.new(@hotel)
  end

  def new
    binding.pry
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(allowed_params)

    if @hotel.save
      redirect_to hotels_path
    else
      render 'new'
    end
  end

  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy
    redirect_to root_path
  end

  private

  def admin?
    unless current_user.role == "admin"
      raise Forbidden, "You are not welcomed here"
    end
  end

  def allowed_params
    params.require(:hotel).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/feedbacks/index.html.erb
<% @feedbacks.each do |feedback| %>
  Hotel Feedback: <%= @feedback.review %><br>
<% end %>

app/views/hotels/index.html.haml
- if user_signed_in?
  %p All hotels list:
  - @hotels.each do |hotel|
    -if current_user.admin?
      %p
        Hotel Name: #{link_to hotel.name, hotel_path(hotel)} --> #{link_to 'Delete', hotel, method: :delete}
    - else
      %p
        Hotel Name: #{link_to hotel.name, hotel_path(hotel)}
- if current_user.admin?
  %div
    #{link_to "Create new hotel", new_hotel_path}

app/views/hotels/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Hotels list", root_path %></li>
    <li class="breadcrumb-item active" aria-current="page">New Hotel</li>
  </ol>
</nav>
<div class="container">
  <div class="row">
    <h1>New hotel page</h1>
    <span class="border border-primary">
      <div class="col-lg-6 form-group" style="background: lightgrey">
        <%= form_for @hotel do |hotel| %>

          <%= hotel.label :name %></br>
          <%= hotel.text_field :name, :class => 'form-control form-control-lg' %></br>

          <%= hotel.label :decription %></br>
          <%= hotel.text_field :description, :class => 'form-control form-control-lg' %></br>

          <%= hotel.submit 'Create hotel', :class => 'btn btn-primary' %>
        <% end %>
      </div>
    </span>
  </div>
</div>

app/views/hotels/show.html.haml
%p
  welcome to the #{@hotel.name} page!
%p
  Hotel Adress:#{@hotel.adress}
  %br/
  Description: #{@hotel.description}
  %br/
%h1 Our Statistics:
Average cleanliness: #{@presenter.cleanliness}
%br/
Average placement: #{@presenter.placement}
%br/
Average communication: #{@presenter.communication}
%h1 Feedbacks:
- @presenter.persisted_feedbacks.each do |feedback|
  Feedback send by: #{feedback.user.email}
  %br/
  Hotel Feedback: #{feedback.review}
  %br/
  Hotel cleanliness: #{feedback.cleanliness}
  %br/
  Hotel communication: #{feedback.communication}
  %br/
  Hotel placement: #{feedback.placement}
  %br/
  %p  
%div
  %h1 New feedback:
  - if @feedback.errors.any?
    #error_explanation
      %h2
        = pluralize(@feedback.errors.count, "error")
        prohibited this feedback from being saved:
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg
  = form_for [@hotel, @feedback] do |f|
    = f.label :review
    %br/
    = f.text_area :review
    %br/
    = f.label :cleanliness
    %br/
    = f.select(:cleanliness, options_for_select([['5'], ['4'],['3'],['2'],['1']]))
    %br/
    = f.label :placement
    %br/
    = f.select(:placement, options_for_select([['5'], ['4'],['3'],['2'],['1']]))
    %br/
    = f.label :communication
    %br/
    = f.select(:communication, options_for_select([['5'], ['4'],['3'],['2'],['1']]))
    %br/
    = f.submit
    %br/

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Home", root_path %>
        </li>
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active">
          <% if current_user %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>